### ISSUE TITLE
Unhandled exception (Windows 10, dual screen)

### ISSUE THREAD

**Issue by JorgenHedlund** [cDima/Aerial#70] opened 2016-06-04 13:43 UTC
System.IO.IOException: The process cannot access the file ...

See attachment -- sorry, can't expand the window as the mouse pointer is disabled.

![unhandledexception](https://cloud.githubusercontent.com/assets/7010726/15799854/0265db8a-2a6b-11e6-8326-cbf2047f627f.JPG)

**Comment by alistairmcmillan** [comment] 2016-06-04 14:10
Hi @JorgenHedlund, when you got this error, can you remember, was the same video playing on both screens?

**Comment by JorgenHedlund** [comment] 2016-06-04 14:28
Interestingly enough there are a few videos playing without the exception --

I've created a thumblist attached to show those that had the exception 



![unhandledexception--screens](https://cloud.githubusercontent.com/assets/7010726/15800109/5f1dffaa-2a71-11e6-93e1-3e3eae34f4d9.JPG)

**Comment by alistairmcmillan** [comment] 2016-06-05 12:19
I think I know what is happening here and I'm working on a fix. Closing this issue though as it's a duplicate of #61 

I still want to make a couple of changes before submitting the fix to @cDima but if you feel like testing I uploaded a version that should eliminate these errors. https://github.com/alistairmcmillan/Aerial-Windows/releases/tag/4.1

**Closed by alistairmcmillan** 2016-06-05 12:20 UTC
