### ISSUE TITLE
Only one video is played

### ISSUE THREAD

**Issue by OussDeCouette** [cDima/Aerial#88] opened 2016-12-24 23:28 UTC
When the screensaver launches, there's only one video, then it freezes, once a video is over, there should be another video starting right ?

**Comment by alistairmcmillan** [comment] 2016-12-25 11:48
A few people are having this issue. There's a discussion already doing under another issue.

Closing as a duplicate of #82.

**Closed by alistairmcmillan** 2016-12-25 11:48 UTC
