### ISSUE TITLE
Black bars on 1440p 

### ISSUE THREAD

**Issue by Sethi-1** [cDima/Aerial#12] opened 2015-11-03 16:11 UTC
Using the Aerial screensaver in Windows 7 with a 1440p resolution, the screensaver is displayed in the middle of the screen at 1080p surrounded by black bars.

**Comment by alistairmcmillan** [comment] 2015-11-04 02:28
Duplicate of #2

**Closed** 2015-11-04 15:36 UTC
Labels: enhancement

**Comment by Sethi-1** [comment] 2015-11-05 07:33
Thanks
