### ISSUE TITLE
Not able to see Change Cache location button

### ISSUE THREAD

**Issue by karthikmangipudi** [cDima/Aerial#101] opened 2017-01-05 03:58 UTC
This screensaver is most stunning. However, it is occupying >10GB space and eating up my C Drive. I have requested a feature which has possibly been implemented. However, I do not see it either in the configure interface or at any other location.
1. Change cache location being placed in the configure interface itself would be awesome.
2. An estimated total space the entire screensaver takes up be present in a sort of warning Readme would help.

**Comment by alistairmcmillan** [comment] 2017-01-05 12:46
If you feel like being a guinea pig you can find a **_pre-release_** here with the Change Cache Location button.

_Note that this is isn't one of Dmitry's releases, so if you do try it you should check back now and again for an official one._

https://github.com/alistairmcmillan/Aerial-Windows/releases/tag/4.0.27

**Comment by alistairmcmillan** [comment] 2017-01-05 21:15
Closing of duplicate of #85.

**Closed by alistairmcmillan** 2017-01-05 21:15 UTC

**Comment by alistairmcmillan** [comment] 2017-01-05 21:25
@karthikmangipudi Meant to say the cache will take up about 12.75GB in total.
