### ISSUE TITLE
won't install

### ISSUE THREAD

**Issue by dglesne** [cDima/Aerial#97] opened 2016-12-31 16:42 UTC
I may be missing something, but it will not let me install.  Forgive me for I am a newbie and doing this for the first time.  I am running Windows 10  on a Dell XPS 8100 with 8 gig ram.  If you can help that would be great!

**Comment by alistairmcmillan** [comment] 2016-12-31 23:32
Closing as a duplicate of #93 .

**Closed by alistairmcmillan** 2016-12-31 23:32 UTC
