### ISSUE TITLE
Monitor isn´t turning off

### ISSUE THREAD

**Issue by seelenfrieden** [cDima/Aerial#29] opened 2015-11-16 22:06 UTC
of I use Aerial. Although timer is set to 20min the monitor isn´t turning off anymore to go in energy saving mode. WIN 10 64bit

**Comment by alistairmcmillan** [comment] 2015-11-16 22:26
Duplicate of #5

**Comment by cDima** [comment] 2015-11-22 05:19
Solved, take a look at the v0.0.3 release, @seelenfrieden.

**Closed by cDima** 2015-11-22 05:19 UTC
