### ISSUE TITLE
Scaling of screensaver

### ISSUE THREAD

**Issue by devbeard** [cDima/Aerial#13] opened 2015-11-03 16:47 UTC
It would be great to have some scaling options for the videos (`No scale/Stretch/Fill`). I have black bars on every side of the video on a `3440x1440` display and would opt to have the video fill my screen (aka no black bars).

**Comment by alistairmcmillan** [comment] 2015-11-03 17:07
Which version of Windows are you running?

**Comment by devbeard** [comment] 2015-11-03 18:14
Windows 10 Pro 64-bit

**Comment by rreynier** [comment] 2015-11-04 02:22
Same here, running 2560 by 1600 with windows 10 64bit. It would be nice to stretch to the screensize.

**Comment by alistairmcmillan** [comment] 2015-11-04 02:27
Duplicate of #12

**Comment by devbeard** [comment] 2015-11-04 08:39
Had a look at this last night, and I have created a pull request that does screen filling by default. People with 16:9 screens should not notice anything different as the videos from Apple are 16:9, but 21:9, 4:3, 3:2 and others should see it filling out (at the cost of normal video scaling in Windows Media Player).

**Comment by cDima** [comment] 2015-11-04 15:37
Thanks @devbeard - your request fixed issue #2.

**Closed by cDima** 2015-11-04 15:37 UTC
