### ISSUE TITLE
Zoom in/Full Screen

### ISSUE THREAD

**Issue by enoteware** [cDima/Aerial#15] opened 2015-11-04 05:57 UTC
Hello,
When running on a 4k display it doesn't auto stretch to full screen or at least give an option.  That would be great.  Thank you!

**Comment by alistairmcmillan** [comment] 2015-11-04 11:21
Duplicate of #2

**Comment by cDima** [comment] 2015-11-04 15:38
@enoteware fixed.

**Closed** 2015-11-04 15:37 UTC

**Comment by enoteware** [comment] 2015-11-04 17:05
Thank you.
