### ISSUE TITLE
very high bandwith

### ISSUE THREAD

**Issue by seelenfrieden** [cDima/Aerial#40] opened 2015-12-13 14:56 UTC
Hi, the screensaver is loading a lot of data down. In the last week it was 33GB. is this the normal behavior, beacause it is streaming the videos? WIll it be possible to limit the bandwith

Best regards
Dennis

**Comment by bytehead-** [comment] 2015-12-13 15:27
I've noticed it myself.  Since I don't usually get to see the screensaver, except for in the morning, I've stopped using it, since I saw that my use was 43GB, and now that Comcast WILL cap my usage, I'm getting picky on what is worth to download and what is not.  Love this screensaver.  Hate what Comcast is doing.

**Comment by alistairmcmillan** [comment] 2015-12-13 23:03
@seelenfrieden @bytehead- Download the latest beta. Cache the videos. That way you'll only download each video once from Apple's servers.

**Comment by alistairmcmillan** [comment] 2015-12-13 23:13
Ignore my previous (now deleted) comment. Wrong repo. This is basically another request for a caching option. Duplicate of #11 .

**Comment by qv1sten** [comment] 2015-12-15 19:28
Mine has used 76.3gb, wtfis this???

**Comment by cDima** [comment] 2015-12-15 19:33
Caching is possible in the latest beta build.

On Tue, Dec 15, 2015 at 2:32 PM, qv1sten <notifications@github.com> wrote:

> Mine has used 76.3gb, wtfis this???
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cDima/Aerial/issues/40#issuecomment-164866826>.
>



-- 
*Dmitry Sadakov *
Consultant – Web Technology  | Gemini Systems | A&M | 600 Madison Ave| New
York, NY | Mobile +16468531955
sadakov.com | linkedin <http://linkedin.com/in/sadakov> | stackoverflow
<http://stackoverflow.com/users/82054/cdima> | github
<https://github.com/cDima> | g+ <http://www.google.com/profiles/sadakov> |
facebook <https://www.facebook.com/sadakov> | vk <http://vk.com/sadakov> |
skype:dmitry.sadakov

**Comment by profjared** [comment] 2015-12-17 01:13
@cDima - where can I find the latest beta build with cacheing?? Thanks for your hard work!

**Comment by cDima** [comment] 2015-12-17 04:15
@profjared you would udually need to compile, but check out the latest [/install](https://github.com/cDima/Aerial/tree/master/install) folder's zip file.

**Closed by cDima** 2015-12-17 04:15 UTC
