### ISSUE TITLE
Offline issue

### ISSUE THREAD

**Issue by kariyann** [cDima/Aerial#123] opened 2017-05-22 13:38 UTC
I'm sorry to repost about this.
I've cached all the videos. When I shut my Wifi interface down, the screensaver don't work, my screen turn black for a few seconds and goes back to desktop, despite the cached videos.
Something thing to try to connect to Internet in order to launch the screensaver. 
Is there a way to bypass this ?

Thank you

**Comment by alistairmcmillan** [comment] 2017-08-08 23:03
Duplicate of #94

**Closed by alistairmcmillan** 2017-08-08 23:03 UTC
