### ISSUE TITLE
Lots of playlists created 

### ISSUE THREAD

**Issue by matthiasg** [cDima/Aerial#20] opened 2015-11-06 15:02 UTC
I found one weird issue. It seems Aerial is creating lots and lots of playlists called Aerial in my default music folder which then appear in Groove.

![image](https://cloud.githubusercontent.com/assets/231889/11000060/d5334178-849f-11e5-8205-5ac0b28999dd.png)

**Comment by alistairmcmillan** [comment] 2015-11-06 15:05
Duplicate of #19

**Closed** 2015-11-06 17:20 UTC
