### ISSUE TITLE
Main monitor has black borders

### ISSUE THREAD

**Issue by matthiasg** [cDima/Aerial#17] opened 2015-11-04 09:51 UTC
I have four monitors with different resolutions. would be nice if the videos always filled the monitors without black borders (touch from outside frame not inside frame so to speak)

**Comment by alistairmcmillan** [comment] 2015-11-04 12:01
Duplicate of #2

**Comment by cDima** [comment] 2015-11-04 15:38
@matthiasg fixed.

**Closed by cDima** 2015-11-04 15:38 UTC

**Comment by matthiasg** [comment] 2015-11-05 12:02
@cDima it is indeed fixed .. great. Sadly my monitor (number 1 in customize your display) is fully black now, while it runs great (also really smooth now) on the other 3 (2,3 and usb connected 4).

any idea ? it used to show up on all 4 before.

PS: I already saw the Aerial Settings checkbox `Disabled all but main screen on 3+ screen setups`. But it was checked initially and still showed on those 3, and after unchecking it still shows on those same 3.

PPS: Great job !

**Comment by cDima** [comment] 2015-11-05 14:44
@matthiasg awesome setup that you have. I fixed the current build and updated the package, please redownload and take a look. I have only two monitors to test with but noticed the hypothetical bug.

**Comment by matthiasg** [comment] 2015-11-05 16:09
Thanks .. Will check it out first thing tomorrow morning :) btw your  screensaver is already better on multi monitor setups than the built in ones :)

**Comment by matthiasg** [comment] 2015-11-06 06:53
Perfect ... Great job !

![wp_20151106_07_32_58_raw](https://cloud.githubusercontent.com/assets/231889/10991018/cdd50c4a-8459-11e5-84bd-13d5717298c7.jpg)


![aerial](https://cloud.githubusercontent.com/assets/231889/10991164/3bbea67a-845b-11e5-9d32-2596a42977c6.gif)

**Comment by cDima** [comment] 2015-11-06 16:36
@matthiasg veeeery impressive setup. May I use the gif on project's description?

**Comment by matthiasg** [comment] 2015-11-09 07:16
@cDima  sure.. if you dont mind all the stuff lying around :D
