### ISSUE TITLE
Running saver prompts Norton to declare suspicious behavior - SONAR.Heuristic.138 

### ISSUE THREAD

**Issue by tgoeke** [cDima/Aerial#52] opened 2015-12-22 04:16 UTC
Running the saver on Windows 10 causes Norton to quarantine the saver .scr file on some computers.  (1 of 2 in my office).

http://www.symantec.com/security_response/writeup.jsp?docid=2015-100115-2953-99

**Comment by alistairmcmillan** [comment] 2015-12-22 09:36
It's a false positive. It's taking a guess "based on certain attributes". Duplicate of #9 .

Which version are you running? Try the latest version. Virus scanners don't make this mistake with the latest version. https://www.virustotal.com/en/file/954b4ac9e8661fdf6b9dc15947ac83689ab051ba0ca9535aa679b2d7deef9ef6/analysis/

**Comment by tgoeke** [comment] 2015-12-22 14:34
I'm using version 3.1

**Comment by tgoeke** [comment] 2015-12-22 14:36
Note, the virustotal scan will always show as passed, Norton does too until you run the saver, then it deletes the file.  So I think this is slightly different.

**Comment by alistairmcmillan** [comment] 2015-12-23 11:42
Norton should have a way to report false positives.

**Closed** 2016-11-14 02:41 UTC
