### ISSUE TITLE
Finally, found the reason why i got a black screensaver

### ISSUE THREAD

**Issue by heeroyuyj** [cDima/Aerial#24] opened 2015-11-09 06:10 UTC
as u mentioned, this scr need WMP, so it can function properly

I did find if I disable AMD Crossfire, the WMP play fine, and so the scr (if I enable Crossfire, WMP occurr errors with playing any video files)

anyway, im happy i can use this scr at last...

also, Aerial Screensaver for Mac got "Caching Support & Offline Mode - Beta"

can we have it on windows?

**Comment by alistairmcmillan** [comment] 2015-11-09 10:49
Caching request duplicate of #11

**Comment by alistairmcmillan** [comment] 2015-11-09 12:16
And solution for #22

**Closed** 2015-11-22 05:20 UTC
