### ISSUE TITLE
Power Settings Bug

### ISSUE THREAD

**Issue by purevertigo** [cDima/Aerial#69] opened 2016-05-29 09:08 UTC
The screensaver does not allow the system to shut off the Monitor/make the monitor go to sleep after a certain time.

**Comment by alistairmcmillan** [comment] 2016-05-30 01:20
Duplicate of #54

**Closed by alistairmcmillan** 2016-05-30 01:20 UTC
Labels: duplicate

**Comment by djhmateer** [comment] 2016-05-30 12:42
Slightly tangential, but if you keyboard shortcut to a 'lock screen' then you can auto power off after any length of time. I like 15mins. http://www.programgood.net/2016/05/24/AerialScreensaverkeyboardShortcutAndNoPowerOff.aspx

**Comment by purevertigo** [comment] 2016-06-05 07:08
This is still a bug.
